[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "node dist/src/server.js"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
