import { AuditConfig } from './types';
import path from 'path';

const config: AuditConfig = {
  outputDir: process.env.OUTPUT_DIR ?? path.join(process.cwd(), 'audit-results'),
  coverageSourceDir: process.env.COVERAGE_SOURCE_DIR
    ?? path.join(process.cwd(), 'audit-results', 'cibil-urls'),
  headless: process.env.HEADLESS === 'true',
  viewport: { width: 1280, height: 800 },
  timeout: 30000,

  pages: [
    // ── Core Pages ─────────────────────────────────────────────────────────
    { name: 'Homepage', url: 'https://www.cibil.com/', waitFor: 'body' },
    { name: 'Document Checklist', url: 'https://www.cibil.com/document-checklist', waitFor: 'body' },
    { name: 'Document Upload', url: 'https://www.cibil.com/document-upload', waitFor: 'body' },
    { name: 'Enquiry CCR', url: 'https://www.cibil.com/enquiryccr', waitFor: 'body' },
    { name: 'Enquiry', url: 'https://www.cibil.com/enquiry', waitFor: 'body' },
    { name: 'Understand How You Will Be Evaluated', url: 'https://www.cibil.com/understand-how-you-will-be-evaluated', waitFor: 'body' },
    { name: '404 Error Page', url: 'https://www.cibil.com/errors/404', waitFor: 'body' },
    { name: 'Consumer Search Results', url: 'https://www.cibil.com/consumer-search-results', waitFor: 'body' },
    { name: 'Free CIBIL Score', url: 'https://www.cibil.com/freecibilscore', waitFor: 'body' },
    { name: 'Consumer', url: 'https://www.cibil.com/consumer', waitFor: 'body' },
    { name: 'Consumer Durable Loan', url: 'https://www.cibil.com/consumer-durable-loan', waitFor: 'body' },
    { name: 'Loans', url: 'https://www.cibil.com/loans', waitFor: 'body' },
    { name: 'Home Loans', url: 'https://www.cibil.com/loans-home', waitFor: 'body' },
    { name: 'Personal Loans', url: 'https://www.cibil.com/personal-loans', waitFor: 'body' },
    { name: 'Auto Loans', url: 'https://www.cibil.com/auto-loans', waitFor: 'body' },
    { name: 'Credit Cards', url: 'https://www.cibil.com/credit-cards', waitFor: 'body' },
    { name: 'Gold Loan', url: 'https://www.cibil.com/gold-loan', waitFor: 'body' },
    { name: 'Types of Commercial Loans', url: 'https://www.cibil.com/types-commercial-loans', waitFor: 'body' },
    { name: 'Commercial Credit', url: 'https://www.cibil.com/commercial-credit', waitFor: 'body' },
    { name: 'Company Credit Report', url: 'https://www.cibil.com/company-credit-report', waitFor: 'body' },
    { name: 'Consumer Dispute Resolution', url: 'https://www.cibil.com/consumer-dispute-resolution', waitFor: 'body' },
    { name: 'Company Dispute Resolution', url: 'https://www.cibil.com/company-dispute-resolution', waitFor: 'body' },
    { name: 'Microfinance Dispute Resolution', url: 'https://www.cibil.com/microfinance-dispute-resolution', waitFor: 'body' },
    { name: 'Complaints and Escalations', url: 'https://www.cibil.com/complaints-and-escalations', waitFor: 'body' },
    { name: 'CIBIL Alerts', url: 'https://www.cibil.com/cibil-alerts', waitFor: 'body' },
    { name: 'Alerts', url: 'https://www.cibil.com/alerts', waitFor: 'body' },
    { name: 'CIBIL App', url: 'https://www.cibil.com/cibil-app', waitFor: 'body' },
    { name: 'Score Simulator', url: 'https://www.cibil.com/score-simulator', waitFor: 'body' },
    { name: 'Loan Calculator', url: 'https://www.cibil.com/loan-calculator', waitFor: 'body' },
    { name: 'Loan Approval Process', url: 'https://www.cibil.com/loan-approval-process', waitFor: 'body' },
    { name: 'Credit Advice', url: 'https://www.cibil.com/credit-advice', waitFor: 'body' },
    { name: 'New to Credit', url: 'https://www.cibil.com/new-to-credit', waitFor: 'body' },
    { name: 'Watch and Learn', url: 'https://www.cibil.com/watch-and-learn', waitFor: 'body' },
    { name: 'Life Events', url: 'https://www.cibil.com/life-events', waitFor: 'body' },
    { name: 'Credit Myths', url: 'https://www.cibil.com/credit-myths', waitFor: 'body' },
    { name: 'Stay Credit Ready', url: 'https://www.cibil.com/stay-credit-ready', waitFor: 'body' },
    { name: 'Microfinance', url: 'https://www.cibil.com/microfinance', waitFor: 'body' },
    { name: 'Official Partners', url: 'https://www.cibil.com/official-partners', waitFor: 'body' },
    { name: 'Nodal Officer List', url: 'https://www.cibil.com/nodal-officer-list', waitFor: 'body' },
    { name: 'Contact Us', url: 'https://www.cibil.com/contact-us', waitFor: 'body' },
    { name: 'Contact', url: 'https://www.cibil.com/contact', waitFor: 'body' },
    { name: 'Contact Us FAQ', url: 'https://www.cibil.com/contact-us-faq', waitFor: 'body' },
    { name: 'Sitemap', url: 'https://www.cibil.com/sitemap', waitFor: 'body' },
    { name: 'Page Not Found', url: 'https://www.cibil.com/pagenotfound', waitFor: 'body' },
    { name: 'Frequent Queries', url: 'https://www.cibil.com/frequent-queries', waitFor: 'body' },
    { name: 'Terms and Conditions', url: 'https://www.cibil.com/terms-and-conditions', waitFor: 'body' },
    { name: 'Privacy Policy', url: 'https://www.cibil.com/privacy-policy', waitFor: 'body' },
    { name: 'Regulatory', url: 'https://www.cibil.com/regulatory', waitFor: 'body' },
    { name: 'Framework for Compensation', url: 'https://www.cibil.com/framework-for-compensation', waitFor: 'body' },
    { name: 'Fraud Prevention', url: 'https://www.cibil.com/fraud-prevention', waitFor: 'body' },
    { name: 'FAQ Brochure', url: 'https://www.cibil.com/faq-brochure', waitFor: 'body' },
    { name: 'RBI Notifications', url: 'https://www.cibil.com/external-links/rbi-notifications', waitFor: 'body' },
    { name: 'Business Code of Conduct', url: 'https://www.cibil.com/external-links/business-code-of-conduct', waitFor: 'body' },
    { name: 'Blog', url: 'https://www.cibil.com/blog', waitFor: 'body' },

    // ── Product / Subscription Landing Pages ─────────────────────────────
    { name: 'Select Plan', url: 'https://www.cibil.com/select-plan', waitFor: 'body' },
    { name: 'Choose Subscription', url: 'https://www.cibil.com/choose-subscription', waitFor: 'body' },
    { name: 'CIBIL Rank (CCR)', url: 'https://www.cibil.com/cibilrank', waitFor: 'body' },

    // ── TransUnion CIBIL Corporate Site ──────────────────────────────────
    { name: 'TU - Homepage', url: 'https://www.transunioncibil.com/', waitFor: 'body' },
    { name: 'TU - About TransUnion CIBIL', url: 'https://www.transunioncibil.com/about-us/about-transunion-cibil', waitFor: 'body' },
    { name: 'TU - Company History', url: 'https://www.transunioncibil.com/about-us/company-history', waitFor: 'body' },
    { name: 'TU - Suit Filed Cases', url: 'https://www.transunioncibil.com/suit-filed-cases/suit-filed-cases', waitFor: 'body' },
    { name: 'TU - Careers', url: 'https://www.transunioncibil.com/careers/careers', waitFor: 'body' },
    { name: 'TU - Become a Member (CERSAI)', url: 'https://www.transunioncibil.com/become-a-member/cersai', waitFor: 'body' },
    { name: 'TU - Privacy Policy', url: 'https://www.transunioncibil.com/legal/privacy-policy', waitFor: 'body' },
    { name: 'TU - Terms and Conditions', url: 'https://www.transunioncibil.com/legal/terms-and-conditions', waitFor: 'body' },

    // ── Subdomains ────────────────────────────────────────────────────────
    { name: 'Document Upload Portal', url: 'https://documentupload.cibil.com/', waitFor: 'body' },
    // Login pages are publicly accessible forms (post-login content requires auth)
    { name: 'MyScore Login (Consumer)', url: 'https://myscore.cibil.com/CreditView/mobilelogin.page?enterprise=CIBIL', waitFor: 'body', requiresAuth: false },
    { name: 'MyScore Login (MFI)', url: 'https://myscore.cibil.com/CreditView/login.page?enterprise=MFI', waitFor: 'body', requiresAuth: false },
    { name: 'MyScore Enroll (Free Annual)', url: 'https://myscore.cibil.com/CreditView/enrollShort_new.page?enterprise=CIBIL&offer=FACRA', waitFor: 'body', requiresAuth: false },
    { name: 'CIBIL Rank CCR Login', url: 'https://cibilrankccr.cibil.com/CreditView/login.page?enterprise=CIBILCOMM', waitFor: 'body', requiresAuth: false },
    // Post-login authenticated pages — skipped until login flow is scripted
    { name: 'MyScore Dashboard (Consumer) [AUTH]', url: 'https://myscore.cibil.com/CreditView/login.page?enterprise=CIBIL', waitFor: 'body', requiresAuth: true },

    // ── FAQ Pages ──────────────────────────────────────────────────────────
    { name: 'FAQ - Loan Rejections & Disputes', url: 'https://www.cibil.com/faq/loan-rejections-disputes', waitFor: 'body' },
    { name: 'FAQ - Purchase & Post-Purchase Help', url: 'https://www.cibil.com/faq/purchase-post-purchase-help', waitFor: 'body' },
    { name: 'FAQ - Score Simulator', url: 'https://www.cibil.com/faq/score-simulator', waitFor: 'body' },
    { name: 'FAQ - Free CIBIL Score & Report', url: 'https://www.cibil.com/faq/free-cibil-score-and-report', waitFor: 'body' },
    { name: 'FAQ - Understand Credit Score & Report', url: 'https://www.cibil.com/faq/understand-your-credit-score-and-report', waitFor: 'body' },
    { name: 'FAQ - Company Credit Report', url: 'https://www.cibil.com/faq/company-credit-report', waitFor: 'body' },
    { name: 'FAQ - Credit Score & Loan Basics', url: 'https://www.cibil.com/faq/credit-score-and-loan-basics', waitFor: 'body' },
    { name: 'FAQ - Consumer Awareness', url: 'https://www.cibil.com/faq/consumer-awareness', waitFor: 'body' },

    // ── Media Center ───────────────────────────────────────────────────────
    { name: 'Media Center 2013', url: 'https://www.cibil.com/mediacenter/2013', waitFor: 'body' },
    { name: 'Media Center 2014', url: 'https://www.cibil.com/mediacenter/2014', waitFor: 'body' },
    { name: 'Media Center 2015', url: 'https://www.cibil.com/mediacenter/2015', waitFor: 'body' },
    { name: 'Media Center 2016', url: 'https://www.cibil.com/mediacenter/2016', waitFor: 'body' },

    // ── Suppandi Campaign Pages ────────────────────────────────────────────
    { name: 'Jaagran', url: 'https://www.cibil.com/jaagran', waitFor: 'body' },
    { name: 'Suppandi - Dream Car', url: 'https://www.cibil.com/suppandi-and-his-dream-car', waitFor: 'body' },
    { name: 'Suppandi - Credit Card', url: 'https://www.cibil.com/suppandi-wants-a-credit-card', waitFor: 'body' },
    { name: 'Suppandi - Dream College', url: 'https://www.cibil.com/suppandi-and-renus-dream-college', waitFor: 'body' },
    { name: 'Suppandi - Neighbourhood Store', url: 'https://www.cibil.com/suppandi-and-the-neighbourhood-store', waitFor: 'body' },
    { name: 'Suppandi - CIBIL Myths', url: 'https://www.cibil.com/suppandi-and-the-cibil-myths', waitFor: 'body' },

    // ── Blog Pages ─────────────────────────────────────────────────────────
    { name: 'Blog - Main', url: 'https://www.cibil.com/blog/main', waitFor: 'body' },
    { name: 'Blog - Millennial Consumer Pattern', url: 'https://www.cibil.com/blog/millennial-consumer-pattern', waitFor: 'body' },
    { name: 'Blog - Credit Ready with Good Habits', url: 'https://www.cibil.com/blog/how-to-be-credit-ready-with-good-credit-habits', waitFor: 'body' },
    { name: 'Blog - Safeguarding Credit Profile Diwali', url: 'https://www.cibil.com/blog/safeguarding-your-credit-profile-this-diwali', waitFor: 'body' },
    { name: 'Blog - Tackle Financial Hardship', url: 'https://www.cibil.com/blog/tackle-financial-hardship-with-calm-and-credit-consciousness', waitFor: 'body' },
    { name: 'Blog - Gold Ornaments and Credit', url: 'https://www.cibil.com/blog/how-your-gold-ornaments-can-help-you-get-access-to-credit', waitFor: 'body' },
    { name: 'Blog - First Time Users Guide', url: 'https://www.cibil.com/blog/first-time-users-guide-to-establishing-credit', waitFor: 'body' },
    { name: 'Blog - Advantages of Positive Credit Profile', url: 'https://www.cibil.com/blog/the-advantages-of-a-positive-credit-profile-and-high-cibil-score', waitFor: 'body' },
    { name: 'Blog - Education Loan Tips for Parents', url: 'https://www.cibil.com/blog/five-things-every-parent-should-know-while-applying-for-education-loan', waitFor: 'body' },
    { name: 'Blog - Business Finance Management', url: 'https://www.cibil.com/blog/ten-ways-to-manage-your-business-finances-effectively', waitFor: 'body' },
    { name: 'Blog - First Time Users Infographic', url: 'https://www.cibil.com/blog/first-time-users-guide-to-establishing-credit-infographic', waitFor: 'body' },
    { name: 'Blog - Women Credit Choices', url: 'https://www.cibil.com/blog/how-womens-credit-choices-are-affecting-he-indian-economic-ecosystem', waitFor: 'body' },
    { name: 'Blog - Bounce Back from Low Score', url: 'https://www.cibil.com/blog/can-you-bounce-back-from-a-low-cibil-score', waitFor: 'body' },
    { name: 'Blog - CIBIL Rank for Business', url: 'https://www.cibil.com/blog/fast-track-your-business-plans-with-cibil-rank', waitFor: 'body' },
    { name: 'Blog - Protect from Credit Fraud', url: 'https://www.cibil.com/blog/four-steps-to-protect-yourself-from-credit-fraud', waitFor: 'body' },
    { name: 'Blog - Credit When Tying the Knot', url: 'https://www.cibil.com/blog/three-credit-facts-to-keep-in-mind-when-tying-the-knot', waitFor: 'body' },
    { name: 'Blog - Cycle of Good Credit', url: 'https://www.cibil.com/blog/cycle-of-good-credit', waitFor: 'body' },
    { name: 'Blog - CIBIL Rank vs CIBIL Score', url: 'https://www.cibil.com/blog/is-there-a-difference-between-cibilrank-and-cibilscore', waitFor: 'body' },
    { name: 'Blog - Key Features of CIBIL Report', url: 'https://www.cibil.com/blog/understand-the-key-features-of-your-cibil-report', waitFor: 'body' },
    { name: 'Blog - CIBIL Score and Car Loan', url: 'https://www.cibil.com/blog/how-does-your-cibil-score-affect-your-car-loan', waitFor: 'body' },
    { name: 'Blog - Shop Without Worrying', url: 'https://www.cibil.com/blog/how-to-shop-without-worrying-about-any-impact-to-your-cibil-score', waitFor: 'body' },
    { name: 'Blog - Impact of Settled Status', url: 'https://www.cibil.com/blog/impact-of-settled-status-on-cibil-score', waitFor: 'body' },
    { name: 'Blog - All About CIBIL Score', url: 'https://www.cibil.com/blog/all-you-need-to-know-about-cibil-score', waitFor: 'body' },
    { name: 'Blog - Failed Credit Card Payments', url: 'https://www.cibil.com/blog/failed-credit-card-payments', waitFor: 'body' },
    { name: 'Blog - Travel Loan Tips', url: 'https://www.cibil.com/blog/four-things-to-consider-when-applying-for-a-travel-loan', waitFor: 'body' },
    { name: 'Blog - Score Simulator', url: 'https://www.cibil.com/blog/taking-informed-credit-decisions-just-got-easier-with-the-score-simulator', waitFor: 'body' },
    { name: 'Blog - CIBIL Score vs Report', url: 'https://www.cibil.com/blog/cibil-score-vs-report', waitFor: 'body' },
    { name: 'Blog - Six Ways to Use Credit Card', url: 'https://www.cibil.com/blog/six-ways-you-can-use-credit-card-for-optimum-credit-score', waitFor: 'body' },
    { name: 'Blog - Changing Face of Women Consumers', url: 'https://www.cibil.com/blog/take-a-look-at-the-changing-face-of-women-consumers-across-india', waitFor: 'body' },
    { name: 'Blog - Credit Consciousness Among Women', url: 'https://www.cibil.com/blog/increased-credit-consciousnes-and-credit-activity-among-indian-women-consumers', waitFor: 'body' },
    { name: 'Blog - Common Credit Mistakes', url: 'https://www.cibil.com/blog/some-of-the-common-credit-mistakes-to-avoid', waitFor: 'body' },
    { name: 'Blog - Three Steps Financial Freedom', url: 'https://www.cibil.com/blog/move-towards-financial-freedom-with-three-steps', waitFor: 'body' },
    { name: 'Blog - Seven Steps Healthy CIBIL Score', url: 'https://www.cibil.com/blog/7-steps-towards-maintaining-healthy-cibil-score', waitFor: 'body' },
    { name: 'Blog - Credit Heavy Vacation', url: 'https://www.cibil.com/blog/life_events_credit-heavy-vacation', waitFor: 'body' },
    { name: 'Blog - Credit Habits of Indian Millennials', url: 'https://www.cibil.com/blog/credit-habits-of-indian-millennial', waitFor: 'body' },
    { name: 'Blog - Rising Credit Consciousness Women', url: 'https://www.cibil.com/blog/a-look-at-the-rising-credit-consciousness-among-woman-consumer', waitFor: 'body' },
    { name: 'Blog - Positive Credit Profile Habits', url: 'https://www.cibil.com/blog/build-a-positive-credit-profile-with-good-credit-habits', waitFor: 'body' },
    { name: 'Blog - Top 5 Tips Credit Health', url: 'https://www.cibil.com/blog/top-5-tips-to-boost-your-credit-health', waitFor: 'body' },
    { name: 'Blog - Financial and Credit Roadmap', url: 'https://www.cibil.com/blog/how-to-create-your-financial-and-credit-roadmap', waitFor: 'body' },
    { name: 'Blog - Safeguarding Credit Profile', url: 'https://www.cibil.com/blog/safeguarding-your-credit-profile', waitFor: 'body' },
    { name: 'Blog - CIBIL Alerts', url: 'https://www.cibil.com/blog/cibil-alerts-a-smarter-safer-way-to-protect-your-financial-identity', waitFor: 'body' },
    { name: 'Blog - GenZ Credit Guide', url: 'https://www.cibil.com/blog/genz-guide-to-getting-started-and-maintaining-good-credit-health', waitFor: 'body' },
    { name: 'Blog - Five Credit Resolutions New Year', url: 'https://www.cibil.com/blog/five-easy-to-meet-credit-resolutions-for-the-new-year', waitFor: 'body' },
    { name: 'Blog - Holiday Shopping Credit Guide', url: 'https://www.cibil.com/blog/your-one-stop-holiday-shopping-credit-guide', waitFor: 'body' },
    { name: 'Blog - Creditworthiness Financial Independence', url: 'https://www.cibil.com/blog/heres-how-creditworthiness-accelerates-your-financial-independence', waitFor: 'body' },
    { name: 'Blog - CIBIL Score and Home Loan', url: 'https://www.cibil.com/blog/how-a-strong-cibil-score-can-help-home-loan-borrowers', waitFor: 'body' },
    { name: 'Blog - Charting Credit Path Together', url: 'https://www.cibil.com/blog/charting-your-credit-path-together', waitFor: 'body' },
    { name: 'Blog - Money Lessons for Kids', url: 'https://www.cibil.com/blog/six-simple-money-lessons-for-kids-an-early-start-towards-financial-success', waitFor: 'body' },
    { name: 'Blog - Mother Money Lessons', url: 'https://www.cibil.com/blog/mother-knows-best-five-simple-money-management-lessons-to-remember', waitFor: 'body' },
    { name: 'Blog - Financial Stability in Twenties', url: 'https://www.cibil.com/blog/set-yourself-up-in-your-twenties-for-financial-stability-in-your-fourties', waitFor: 'body' },
    { name: 'Blog - Financial Foundation for Young Indians', url: 'https://www.cibil.com/blog/building-a-strong-financial-foundation-essential-money-skills-for-young-indians', waitFor: 'body' },
    { name: 'Blog - New to Credit Healthy Score', url: 'https://www.cibil.com/blog/new-to-credit-heres-how-to-maintain-a-healthy-cibil-score', waitFor: 'body' },
    { name: 'Blog - Festive Season Responsible Credit', url: 'https://www.cibil.com/blog/achieve-your-dreams-this-festive-season-through-responsible-credit-use', waitFor: 'body' },
    { name: 'Blog - Gold Loan Decoding', url: 'https://www.cibil.com/blog/decoding-gold-loan-understanding-the-credit-value-of-gold', waitFor: 'body' },
    { name: 'Blog - Unknown Credit Enquiry', url: 'https://www.cibil.com/blog/what-to-do-if-you-dont-recognize-a-credit-enquiry-on-your-CIBIL-Report', waitFor: 'body' },
    { name: 'Blog - Business Loan Eligibility', url: 'https://www.cibil.com/blog/how-to-supercharge-business-loan-eligibility', waitFor: 'body' },
    { name: 'Blog - Good Credit Habits for Business', url: 'https://www.cibil.com/blog/good-credit-habits-for-a-business-for-a-strong-cibil-rank', waitFor: 'body' },
    { name: 'Blog - Smart Borrowing Strategies', url: 'https://www.cibil.com/blog/six-smart-borrowing-strategies-for-long-term-financial-health', waitFor: 'body' },
    { name: 'Blog - CIBIL Rank and Company Report', url: 'https://www.cibil.com/blog/unlocking-potential-with-cibil-rank-and-company-credit-report', waitFor: 'body' },
    { name: 'Blog - Why Did I Get an Enquiry', url: 'https://www.cibil.com/blog/why-did-I-get-an-enquiry-on-my-credit-report', waitFor: 'body' },
    { name: 'Blog - Be the Boss of Your Money', url: 'https://www.cibil.com/blog/be-the-boss-of-your-own-money', waitFor: 'body' },
    { name: 'Blog - Credit at Every Life Stage', url: 'https://www.cibil.com/blog/credit-matters-at-every-important-stage-in-your-life', waitFor: 'body' },
    { name: 'Blog - Financial Self-Reliance', url: 'https://www.cibil.com/blog/how-financial-self-reliance-can-improve-your-quality-of-life', waitFor: 'body' },
    { name: 'Blog - Money Lessons for Women', url: 'https://www.cibil.com/blog/seven-money-management-lessons-for-women', waitFor: 'body' },
    { name: 'Blog - Tips for Entrepreneurs', url: 'https://www.cibil.com/blog/six-money-management-tips-for-budding-entrepreneurs', waitFor: 'body' },
    { name: 'Blog - Questions Before Personal Loan', url: 'https://www.cibil.com/blog/before-taking-a-personal-loan-ask-yourself-these-questions', waitFor: 'body' },
    { name: 'Blog - What is CIBIL Score', url: 'https://www.cibil.com/blog/what-is-cibil-score', waitFor: 'body' },
    { name: 'Blog - One Month CIBIL Subscription', url: 'https://www.cibil.com/blog/why-a-one-month-cibil-subscription-is-essential-for-your-financial-health', waitFor: 'body' },
    { name: 'Blog - Identify a Scam', url: 'https://www.cibil.com/blog/how-to-identify-a-scam-protect-yourself-from-fake-customer-care-calls', waitFor: 'body' },
    { name: 'Blog - Protect from Scams', url: 'https://www.cibil.com/blog/how-to-protect-yourself-from-scams-and-fraudulent-activity', waitFor: 'body' },
    { name: 'Blog - Love Marriage and CIBIL Scores', url: 'https://www.cibil.com/blog/love-marriage-and-cibil-scores-why-your-financial-health-matters', waitFor: 'body' },
    { name: 'Blog - Malicious Apps Guide', url: 'https://www.cibil.com/blog/staying-safe-in-the-digital-age-guide-to-spotting-and-avoiding-malicious-apps', waitFor: 'body' },
    { name: 'Blog - Guide to Securing Business Loan', url: 'https://www.cibil.com/blog/guide-to-securing-business-loan', waitFor: 'body' },
    { name: 'Blog - Power of Good Credit Habits', url: 'https://www.cibil.com/blog/power-of-good-credit-habits', waitFor: 'body' },
    { name: 'Blog - Credit Positive New Financial Year', url: 'https://www.cibil.com/blog/your-checklist-for-a-credit-positive-start-to-the-new-financial-year', waitFor: 'body' },
    { name: 'Blog - WhatsApp Scam Story', url: 'https://www.cibil.com/blog/how-a-whatsapp-image-turned-out-to-be-a-scam', waitFor: 'body' },
    { name: 'Blog - Small Business Loan Eligibility', url: 'https://www.cibil.com/blog/how-small-businesses-can-improve-loan-eligibility', waitFor: 'body' },
    { name: 'Blog - Data Encryption Fraud Defense', url: 'https://www.cibil.com/blog/level-up-your-fraud-defense-with-data-encryption', waitFor: 'body' },
    { name: 'Blog - Path to Creditworthiness', url: 'https://www.cibil.com/blog/the-path-to-creditworthiness', waitFor: 'body' },
    { name: 'Blog - Regularly Checking CIBIL Report', url: 'https://www.cibil.com/blog/why-regularly-checking-your-cibil-report-matters-more-than-ever', waitFor: 'body' },
    { name: 'Blog - Check Free CIBIL Score Once a Year', url: 'https://www.cibil.com/blog/check-your-free-cibil-score-once-a-calendar-year', waitFor: 'body' },
    { name: 'Blog - Closing a Credit Card Checklist', url: 'https://www.cibil.com/blog/closing-a-credit-card-heres-your-dos-and-donts-checklist', waitFor: 'body' },
    { name: 'Blog - Credit Marathon', url: 'https://www.cibil.com/blog/credit-marathon-how-to-train-your-way-to-a-strong-credit-history', waitFor: 'body' },
    { name: 'Blog - Key Checks Before Car Loan', url: 'https://www.cibil.com/blog/key-checks-prior-to-applying-for-a-car-loan', waitFor: 'body' },
    { name: 'Blog - Smarter Spending Festive Season', url: 'https://www.cibil.com/blog/celebrate-more-worry-less-smarter-spending-this-festive-season', waitFor: 'body' },
    { name: 'Blog - Monsoon Finance Catch Up', url: 'https://www.cibil.com/blog/when-the-rains-slow-you-down-let-your-finances-catch-up', waitFor: 'body' },
    { name: 'Blog - Shopping Wisely Online and Offline', url: 'https://www.cibil.com/blog/from-cart-to-credit-shopping-wisely-online-and-offline', waitFor: 'body' },
    { name: 'Blog - Business Financial Discipline', url: 'https://www.cibil.com/blog/business-success-that-is-built-on-the-pillars-of-financial-discipline', waitFor: 'body' },
    { name: 'Blog - Gold Prices Festive Family Plans', url: 'https://www.cibil.com/blog/the-golden-touch-how-rising-prices-impact-your-festive-family-plans', waitFor: 'body' },
    { name: 'Blog - Festive Season Finance', url: 'https://www.cibil.com/blog/festive-season-finance-gold-loans-personal-loans-and-your-cibil-score', waitFor: 'body' },
    { name: 'Blog - CIBIL Dispute Resolution Guide', url: 'https://www.cibil.com/blog/a-guide-to-cibil-dispute-resolution-process', waitFor: 'body' },
    { name: 'Blog - Financing Before and After Wedding', url: 'https://www.cibil.com/blog/financing-forever-credit-choices-before-and-after-the-wedding', waitFor: 'body' },
    { name: 'Blog - Vacation with Credit', url: 'https://www.cibil.com/blog/vacation-on-your-mind-credit-by-your-side', waitFor: 'body' },
    { name: 'Blog - Swipe Smart Credit Habits', url: 'https://www.cibil.com/blog/swipe-smart-how-your-mind-shapes-your-credit-habits', waitFor: 'body' },
    { name: 'Blog - Stay Merry Festive Season', url: 'https://www.cibil.com/blog/stay-merry-this-festive-season-keep-your-cibil-score-sparkling', waitFor: 'body' },
    { name: 'Blog - Credit Health New Year Resolutions', url: 'https://www.cibil.com/blog/your-credit-health-cheat-sheet-how-to-stick-to-your-financial-new-years-resolutions', waitFor: 'body' },
    { name: 'Blog - Credit Mix Made Simple', url: 'https://www.cibil.com/blog/credit-mix-made-simple-why-the-right-balance-matters-for-your-credit-health', waitFor: 'body' },
    { name: 'Blog - Walk Through CIBIL Report Sections', url: 'https://www.cibil.com/blog/walk-through-reading-accounts-enquiries-sections-in-your-cibil-report', waitFor: 'body' },
    { name: 'Blog - Entrepreneurs Credit Mistakes', url: 'https://www.cibil.com/blog/common-credit-mistakes-entrepreneurs-make-and-how-to-avoid-them', waitFor: 'body' },
    { name: 'Blog - Credit Setup Habit Stacking', url: 'https://www.cibil.com/blog/credit-setup-how-to-build-a-habit-stacked-credit-routine-that-actually-sticks', waitFor: 'body' },
    { name: 'Blog - New Credit Card Storybook', url: 'https://www.cibil.com/blog/new-credit-card-your-storybook-of-healthy-credit-habits-begins-here', waitFor: 'body' },
    { name: 'Blog - CIBIL Score Beyond Loan Approvals', url: 'https://www.cibil.com/blog/why-your-cibil-score-matters-beyond-loan-approvals', waitFor: 'body' },

    // ── Hindi (hi) Pages ───────────────────────────────────────────────────
    { name: 'HI - Homepage', url: 'https://www.cibil.com/hi', waitFor: 'body' },
    { name: 'HI - Consumer', url: 'https://www.cibil.com/hi/consumer', waitFor: 'body' },
    { name: 'HI - Alerts', url: 'https://www.cibil.com/hi/alerts', waitFor: 'body' },
    { name: 'HI - Free CIBIL Score', url: 'https://www.cibil.com/hi/freecibilscore', waitFor: 'body' },
    { name: 'HI - Score Simulator', url: 'https://www.cibil.com/hi/score-simulator', waitFor: 'body' },
    { name: 'HI - Company Credit Report', url: 'https://www.cibil.com/hi/company-credit-report', waitFor: 'body' },
    { name: 'HI - Microfinance', url: 'https://www.cibil.com/hi/microfinance', waitFor: 'body' },
    { name: 'HI - FAQ Brochure', url: 'https://www.cibil.com/hi/faq-brochure', waitFor: 'body' },
    { name: 'HI - FAQ Credit Score & Loan Basics', url: 'https://www.cibil.com/hi/faq/credit-score-and-loan-basics', waitFor: 'body' },
    { name: 'HI - FAQ Loan Rejections & Disputes', url: 'https://www.cibil.com/hi/faq/loan-rejections-disputes', waitFor: 'body' },
    { name: 'HI - Loans', url: 'https://www.cibil.com/hi/loans', waitFor: 'body' },
    { name: 'HI - FAQ Understand Credit Score & Report', url: 'https://www.cibil.com/hi/faq/understand-your-credit-score-and-report', waitFor: 'body' },
    { name: 'HI - FAQ Score Simulator', url: 'https://www.cibil.com/hi/faq/score-simulator', waitFor: 'body' },
    { name: 'HI - FAQ Purchase & Post-Purchase Help', url: 'https://www.cibil.com/hi/faq/purchase-post-purchase-help', waitFor: 'body' },
    { name: 'HI - FAQ Free CIBIL Score & Report', url: 'https://www.cibil.com/hi/faq/free-cibil-score-and-report', waitFor: 'body' },
    { name: 'HI - FAQ Company Credit Report', url: 'https://www.cibil.com/hi/faq/company-credit-report', waitFor: 'body' },
    { name: 'HI - Credit Advice', url: 'https://www.cibil.com/hi/credit-advice', waitFor: 'body' },
    { name: 'HI - Credit Myths', url: 'https://www.cibil.com/hi/credit-myths', waitFor: 'body' },
    { name: 'HI - Watch and Learn', url: 'https://www.cibil.com/hi/watch-and-learn', waitFor: 'body' },
    { name: 'HI - MSME Credit', url: 'https://www.cibil.com/hi/msme-credit', waitFor: 'body' },
    { name: 'HI - New to Credit', url: 'https://www.cibil.com/hi/new-to-credit', waitFor: 'body' },
    { name: 'HI - Consumer Dispute Resolution', url: 'https://www.cibil.com/hi/consumer-dispute-resolution', waitFor: 'body' },
    { name: 'HI - Company Dispute Resolution', url: 'https://www.cibil.com/hi/company-dispute-resolution', waitFor: 'body' },
    { name: 'HI - Enquiry', url: 'https://www.cibil.com/hi/enquiry', waitFor: 'body' },
    { name: 'HI - Framework for Compensation', url: 'https://www.cibil.com/hi/frameworkforcompensation', waitFor: 'body' },
    { name: 'HI - Contact Us', url: 'https://www.cibil.com/hi/contact-us', waitFor: 'body' },
    { name: 'HI - About TransUnion CIBIL', url: 'https://www.cibil.com/hi/about-us/about-transunion-cibil', waitFor: 'body' },
    { name: 'HI - Company History', url: 'https://www.cibil.com/hi/about-us/company-history', waitFor: 'body' },
    { name: 'HI - Sitemap', url: 'https://www.cibil.com/hi/sitemap', waitFor: 'body' },
    { name: 'HI - Blog CIBIL Alerts', url: 'https://www.cibil.com/hi/blog/cibil-alerts-a-smarter-safer-way-to-protect-your-financial-identity', waitFor: 'body' },
    { name: 'HI - Blog Bounce Back Low Score', url: 'https://www.cibil.com/hi/blog/can-you-bounce-back-from-a-low-cibil-score', waitFor: 'body' },
    { name: 'HI - Blog Access to Credit Business', url: 'https://www.cibil.com/hi/blog/want-to-improve-access-to-credit-for-your-business', waitFor: 'body' },
    { name: 'HI - Blog First Time Users Infographic', url: 'https://www.cibil.com/hi/blog/first-time-users-guide-to-establishing-credit-infographic', waitFor: 'body' },
    { name: 'HI - Blog New to Credit Healthy Score', url: 'https://www.cibil.com/hi/blog/new-to-credit-heres-how-to-maintain-a-healthy-cibil-score', waitFor: 'body' },
    { name: 'HI - Blog Common Credit Mistakes', url: 'https://www.cibil.com/hi/blog/some-of-the-common-credit-mistakes-to-avoid', waitFor: 'body' },
    { name: 'HI - Blog Positive Credit Profile Habits', url: 'https://www.cibil.com/hi/blog/build-a-positive-credit-profile-with-good-credit-habits', waitFor: 'body' },
    { name: 'HI - Blog Impact of Settled Status', url: 'https://www.cibil.com/hi/blog/impact-of-settled-status-on-cibil-score', waitFor: 'body' },
    { name: 'HI - Blog MSME Loan Access', url: 'https://www.cibil.com/hi/blog/paving-the-way-for-faster-access-to-loans-for-msme', waitFor: 'body' },

    // ── Tamil (ta) Pages ───────────────────────────────────────────────────
    { name: 'TA - Homepage', url: 'https://www.cibil.com/ta', waitFor: 'body' },
    { name: 'TA - Consumer', url: 'https://www.cibil.com/ta/consumer', waitFor: 'body' },
    { name: 'TA - Alerts', url: 'https://www.cibil.com/ta/alerts', waitFor: 'body' },
    { name: 'TA - Free CIBIL Score', url: 'https://www.cibil.com/ta/freecibilscore', waitFor: 'body' },
    { name: 'TA - Score Simulator', url: 'https://www.cibil.com/ta/score-simulator', waitFor: 'body' },
    { name: 'TA - Company Credit Report', url: 'https://www.cibil.com/ta/company-credit-report', waitFor: 'body' },
    { name: 'TA - Microfinance', url: 'https://www.cibil.com/ta/microfinance', waitFor: 'body' },
    { name: 'TA - FAQ Brochure', url: 'https://www.cibil.com/ta/faq-brochure', waitFor: 'body' },
    { name: 'TA - FAQ Credit Score & Loan Basics', url: 'https://www.cibil.com/ta/faq/credit-score-and-loan-basics', waitFor: 'body' },
    { name: 'TA - FAQ Loan Rejections & Disputes', url: 'https://www.cibil.com/ta/faq/loan-rejections-disputes', waitFor: 'body' },
    { name: 'TA - FAQ Consumer Awareness', url: 'https://www.cibil.com/ta/faq/consumer-awareness', waitFor: 'body' },
    { name: 'TA - FAQ ECLGS', url: 'https://www.cibil.com/ta/faq/eclgs', waitFor: 'body' },
    { name: 'TA - Loans', url: 'https://www.cibil.com/ta/loans', waitFor: 'body' },
    { name: 'TA - FAQ Understand Credit Score & Report', url: 'https://www.cibil.com/ta/faq/understand-your-credit-score-and-report', waitFor: 'body' },
    { name: 'TA - FAQ Score Simulator', url: 'https://www.cibil.com/ta/faq/score-simulator', waitFor: 'body' },
    { name: 'TA - FAQ Purchase & Post-Purchase Help', url: 'https://www.cibil.com/ta/faq/purchase-post-purchase-help', waitFor: 'body' },
    { name: 'TA - FAQ Free CIBIL Score & Report', url: 'https://www.cibil.com/ta/faq/free-cibil-score-and-report', waitFor: 'body' },
    { name: 'TA - FAQ Company Credit Report', url: 'https://www.cibil.com/ta/faq/company-credit-report', waitFor: 'body' },
    { name: 'TA - Credit Advice', url: 'https://www.cibil.com/ta/credit-advice', waitFor: 'body' },
    { name: 'TA - Credit Myths', url: 'https://www.cibil.com/ta/credit-myths', waitFor: 'body' },
    { name: 'TA - Watch and Learn', url: 'https://www.cibil.com/ta/watch-and-learn', waitFor: 'body' },
    { name: 'TA - MSME Credit', url: 'https://www.cibil.com/ta/msme-credit', waitFor: 'body' },
    { name: 'TA - New to Credit', url: 'https://www.cibil.com/ta/new-to-credit', waitFor: 'body' },
    { name: 'TA - Consumer Dispute Resolution', url: 'https://www.cibil.com/ta/consumer-dispute-resolution', waitFor: 'body' },
    { name: 'TA - Company Dispute Resolution', url: 'https://www.cibil.com/ta/company-dispute-resolution', waitFor: 'body' },
    { name: 'TA - Enquiry', url: 'https://www.cibil.com/ta/enquiry', waitFor: 'body' },
    { name: 'TA - Framework for Compensation', url: 'https://www.cibil.com/ta/framework-for-compensation', waitFor: 'body' },
    { name: 'TA - Select Plan', url: 'https://www.cibil.com/ta/select-plan2', waitFor: 'body' },
    { name: 'TA - Blog CIBIL Alerts', url: 'https://www.cibil.com/ta/blog/cibil-alerts-a-smarter-safer-way-to-protect-your-financial-identity', waitFor: 'body' },
    { name: 'TA - Blog Bounce Back Low Score', url: 'https://www.cibil.com/ta/blog/can-you-bounce-back-from-a-low-cibil-score', waitFor: 'body' },
    { name: 'TA - Blog Access to Credit Business', url: 'https://www.cibil.com/ta/blog/want-to-improve-access-to-credit-for-your-business', waitFor: 'body' },
    { name: 'TA - Blog First Time Users Infographic', url: 'https://www.cibil.com/ta/blog/first-time-users-guide-to-establishing-credit-infographic', waitFor: 'body' },
    { name: 'TA - Blog New to Credit Healthy Score', url: 'https://www.cibil.com/ta/blog/new-to-credit-heres-how-to-maintain-a-healthy-cibil-score', waitFor: 'body' },
    { name: 'TA - Blog Common Credit Mistakes', url: 'https://www.cibil.com/ta/blog/some-of-the-common-credit-mistakes-to-avoid', waitFor: 'body' },
    { name: 'TA - Blog Positive Credit Profile Habits', url: 'https://www.cibil.com/ta/blog/build-a-positive-credit-profile-with-good-credit-habits', waitFor: 'body' },
    { name: 'TA - Blog Impact of Settled Status', url: 'https://www.cibil.com/ta/blog/impact-of-settled-status-on-cibil-score', waitFor: 'body' },
    { name: 'TA - Blog MSME Loan Access', url: 'https://www.cibil.com/ta/blog/paving-the-way-for-faster-access-to-loans-for-msme', waitFor: 'body' },

    // ── Telugu (te) Pages ──────────────────────────────────────────────────
    { name: 'TE - Homepage', url: 'https://www.cibil.com/te', waitFor: 'body' },
    { name: 'TE - Consumer', url: 'https://www.cibil.com/te/consumer', waitFor: 'body' },
    { name: 'TE - Alerts', url: 'https://www.cibil.com/te/alerts', waitFor: 'body' },
    { name: 'TE - Free CIBIL Score', url: 'https://www.cibil.com/te/freecibilscore', waitFor: 'body' },
    { name: 'TE - Score Simulator', url: 'https://www.cibil.com/te/score-simulator', waitFor: 'body' },
    { name: 'TE - Company Credit Report', url: 'https://www.cibil.com/te/company-credit-report', waitFor: 'body' },
    { name: 'TE - Microfinance', url: 'https://www.cibil.com/te/microfinance', waitFor: 'body' },
    { name: 'TE - FAQ Brochure', url: 'https://www.cibil.com/te/faq-brochure', waitFor: 'body' },
    { name: 'TE - FAQ Credit Score & Loan Basics', url: 'https://www.cibil.com/te/faq/credit-score-and-loan-basics', waitFor: 'body' },
    { name: 'TE - FAQ Loan Rejections & Disputes', url: 'https://www.cibil.com/te/faq/loan-rejections-disputes', waitFor: 'body' },
    { name: 'TE - FAQ Consumer Awareness', url: 'https://www.cibil.com/te/faq/consumer-awareness', waitFor: 'body' },
    { name: 'TE - Loans', url: 'https://www.cibil.com/te/loans', waitFor: 'body' },
    { name: 'TE - FAQ Understand Credit Score & Report', url: 'https://www.cibil.com/te/faq/understand-your-credit-score-and-report', waitFor: 'body' },
    { name: 'TE - FAQ Score Simulator', url: 'https://www.cibil.com/te/faq/score-simulator', waitFor: 'body' },
    { name: 'TE - FAQ Purchase & Post-Purchase Help', url: 'https://www.cibil.com/te/faq/purchase-post-purchase-help', waitFor: 'body' },
    { name: 'TE - FAQ Free CIBIL Score & Report', url: 'https://www.cibil.com/te/faq/free-cibil-score-and-report', waitFor: 'body' },
    { name: 'TE - FAQ Company Credit Report', url: 'https://www.cibil.com/te/faq/company-credit-report', waitFor: 'body' },
    { name: 'TE - Credit Advice', url: 'https://www.cibil.com/te/credit-advice', waitFor: 'body' },
    { name: 'TE - Credit Myths', url: 'https://www.cibil.com/te/credit-myths', waitFor: 'body' },
    { name: 'TE - Watch and Learn', url: 'https://www.cibil.com/te/watch-and-learn', waitFor: 'body' },
    { name: 'TE - MSME Credit', url: 'https://www.cibil.com/te/msme-credit', waitFor: 'body' },
    { name: 'TE - New to Credit', url: 'https://www.cibil.com/te/new-to-credit', waitFor: 'body' },
    { name: 'TE - Consumer Dispute Resolution', url: 'https://www.cibil.com/te/consumer-dispute-resolution', waitFor: 'body' },
    { name: 'TE - Company Dispute Resolution', url: 'https://www.cibil.com/te/company-dispute-resolution', waitFor: 'body' },
    { name: 'TE - Enquiry', url: 'https://www.cibil.com/te/enquiry', waitFor: 'body' },
    { name: 'TE - Framework for Compensation', url: 'https://www.cibil.com/te/framework-for-compensation', waitFor: 'body' },
    { name: 'TE - Blog CIBIL Alerts', url: 'https://www.cibil.com/te/blog/cibil-alerts-a-smarter-safer-way-to-protect-your-financial-identity', waitFor: 'body' },
    { name: 'TE - Blog Bounce Back Low Score', url: 'https://www.cibil.com/te/blog/can-you-bounce-back-from-a-low-cibil-score', waitFor: 'body' },
    { name: 'TE - Blog Access to Credit Business', url: 'https://www.cibil.com/te/blog/want-to-improve-access-to-credit-for-your-business', waitFor: 'body' },
    { name: 'TE - Blog First Time Users Infographic', url: 'https://www.cibil.com/te/blog/first-time-users-guide-to-establishing-credit-infographic', waitFor: 'body' },
    { name: 'TE - Blog New to Credit Healthy Score', url: 'https://www.cibil.com/te/blog/new-to-credit-heres-how-to-maintain-a-healthy-cibil-score', waitFor: 'body' },
    { name: 'TE - Blog Common Credit Mistakes', url: 'https://www.cibil.com/te/blog/some-of-the-common-credit-mistakes-to-avoid', waitFor: 'body' },
    { name: 'TE - Blog Positive Credit Profile Habits', url: 'https://www.cibil.com/te/blog/build-a-positive-credit-profile-with-good-credit-habits', waitFor: 'body' },
    { name: 'TE - Blog Impact of Settled Status', url: 'https://www.cibil.com/te/blog/impact-of-settled-status-on-cibil-score', waitFor: 'body' },
    { name: 'TE - Blog MSME Loan Access', url: 'https://www.cibil.com/te/blog/paving-the-way-for-faster-access-to-loans-for-msme', waitFor: 'body' },

    // ── Bengali (bn) Pages ─────────────────────────────────────────────────
    { name: 'BN - Homepage', url: 'https://www.cibil.com/bn', waitFor: 'body' },
    { name: 'BN - Consumer', url: 'https://www.cibil.com/bn/consumer', waitFor: 'body' },
    { name: 'BN - Alerts', url: 'https://www.cibil.com/bn/alerts', waitFor: 'body' },
    { name: 'BN - Free CIBIL Score', url: 'https://www.cibil.com/bn/freecibilscore', waitFor: 'body' },
    { name: 'BN - Score Simulator', url: 'https://www.cibil.com/bn/score-simulator', waitFor: 'body' },
    { name: 'BN - Company Credit Report', url: 'https://www.cibil.com/bn/company-credit-report', waitFor: 'body' },
    { name: 'BN - Microfinance', url: 'https://www.cibil.com/bn/microfinance', waitFor: 'body' },
    { name: 'BN - FAQ Brochure', url: 'https://www.cibil.com/bn/faq-brochure', waitFor: 'body' },
    { name: 'BN - FAQ Credit Score & Loan Basics', url: 'https://www.cibil.com/bn/faq/credit-score-and-loan-basics', waitFor: 'body' },
    { name: 'BN - FAQ Loan Rejections & Disputes', url: 'https://www.cibil.com/bn/faq/loan-rejections-disputes', waitFor: 'body' },
    { name: 'BN - FAQ Consumer Awareness', url: 'https://www.cibil.com/bn/faq/consumer-awareness', waitFor: 'body' },
    { name: 'BN - Loans', url: 'https://www.cibil.com/bn/loans', waitFor: 'body' },
    { name: 'BN - FAQ Understand Credit Score & Report', url: 'https://www.cibil.com/bn/faq/understand-your-credit-score-and-report', waitFor: 'body' },
    { name: 'BN - FAQ Score Simulator', url: 'https://www.cibil.com/bn/faq/score-simulator', waitFor: 'body' },
    { name: 'BN - FAQ Purchase & Post-Purchase Help', url: 'https://www.cibil.com/bn/faq/purchase-post-purchase-help', waitFor: 'body' },
    { name: 'BN - FAQ Free CIBIL Score & Report', url: 'https://www.cibil.com/bn/faq/free-cibil-score-and-report', waitFor: 'body' },
    { name: 'BN - FAQ Company Credit Report', url: 'https://www.cibil.com/bn/faq/company-credit-report', waitFor: 'body' },
    { name: 'BN - Credit Advice', url: 'https://www.cibil.com/bn/credit-advice', waitFor: 'body' },
    { name: 'BN - Credit Myths', url: 'https://www.cibil.com/bn/credit-myths', waitFor: 'body' },
    { name: 'BN - Watch and Learn', url: 'https://www.cibil.com/bn/watch-and-learn', waitFor: 'body' },
    { name: 'BN - MSME Credit', url: 'https://www.cibil.com/bn/msme-credit', waitFor: 'body' },
    { name: 'BN - New to Credit', url: 'https://www.cibil.com/bn/new-to-credit', waitFor: 'body' },
    { name: 'BN - Consumer Dispute Resolution', url: 'https://www.cibil.com/bn/consumer-dispute-resolution', waitFor: 'body' },
    { name: 'BN - Company Dispute Resolution', url: 'https://www.cibil.com/bn/company-dispute-resolution', waitFor: 'body' },
    { name: 'BN - Enquiry', url: 'https://www.cibil.com/bn/enquiry', waitFor: 'body' },
    { name: 'BN - Framework for Compensation', url: 'https://www.cibil.com/bn/framework-for-compensation', waitFor: 'body' },
    { name: 'BN - Select Plan', url: 'https://www.cibil.com/bn/select-plan2', waitFor: 'body' },
    { name: 'BN - Blog CIBIL Alerts', url: 'https://www.cibil.com/bn/blog/cibil-alerts-a-smarter-safer-way-to-protect-your-financial-identity', waitFor: 'body' },
    { name: 'BN - Blog Bounce Back Low Score', url: 'https://www.cibil.com/bn/blog/can-you-bounce-back-from-a-low-cibil-score', waitFor: 'body' },
    { name: 'BN - Blog Access to Credit Business', url: 'https://www.cibil.com/bn/blog/want-to-improve-access-to-credit-for-your-business', waitFor: 'body' },
    { name: 'BN - Blog First Time Users Infographic', url: 'https://www.cibil.com/bn/blog/first-time-users-guide-to-establishing-credit-infographic', waitFor: 'body' },
    { name: 'BN - Blog New to Credit Healthy Score', url: 'https://www.cibil.com/bn/blog/new-to-credit-heres-how-to-maintain-a-healthy-cibil-score', waitFor: 'body' },
    { name: 'BN - Blog Common Credit Mistakes', url: 'https://www.cibil.com/bn/blog/some-of-the-common-credit-mistakes-to-avoid', waitFor: 'body' },
    { name: 'BN - Blog Positive Credit Profile Habits', url: 'https://www.cibil.com/bn/blog/build-a-positive-credit-profile-with-good-credit-habits', waitFor: 'body' },
    { name: 'BN - Blog Impact of Settled Status', url: 'https://www.cibil.com/bn/blog/impact-of-settled-status-on-cibil-score', waitFor: 'body' },
    { name: 'BN - Blog MSME Loan Access', url: 'https://www.cibil.com/bn/blog/paving-the-way-for-faster-access-to-loans-for-msme', waitFor: 'body' },
  ],
};

export default config;
